site_name: 芯橙数码

pages:
    - 主页: index.md
    - 关于: about.md

extra_css:
    - css/extra.css

markdown_extensions:
    - smarty
    - sane_lists
    - toc:
        permalink: True
    - admonition:

copyright: Copyright &copy; 2017 <a href="http://orro.xyz">OC Digital</a>, Maintained by the <a href="http://orro.xyz">Jamesdog</a>.

docs_dir: 'pages'
site_dir: 'docs'
